---
title: "Sports Program Data Dictionary"
format: html
---

## List of variables:

1. **Year** Year data was collected
2. **unitid** Unique code which identifies institutions
3. **institution_name** Name of institution
4. **city_txt** City in which institution is located
5. **state_cd** 2 digit state code identifying the university
6. **zip_text** 5 digit zip code where the university is located
7. **classification_code** Numerical code which identifies the sports division in which the school belongs. Note that these are structured by the overall division (Division I, II, III etc) and also some
other features such as whether there is an American Football team and which grouping that football team competes in.
8. **classification_name** Name of the classification the university sports teams belong to
9. **classification_other** Description of classification if university belongs to a different sports 
league than the one enumerated previously
10. **ef_male_count** Count of males in the student body
11. **ef_female_count** Count of females in the student body
12. **ef_total_count** Total number of students at the institution
13. **sector_cd** Numeric code identifying the type of university
14. **sector_name** Description of university type
15. **sportscode** Numeric code identifying the sport that the team plays
16. **partic_men** Number of men participating on men's team
17. **partic_women** Number of women participating on women's team
18. **partic_coed_men** Number of men participating on coed team
19. **partic_coed_women** Number of women participating on coed team
20. **sum_partic_men** Sum of men participating in this sport
21. **sum_partic_women** Sum of women participating in this sport
22. **rev_men** Revenue generated by Men's Team
23. **rev_women** Revenue generated by Women's Team
24. **total_rev_men_women** Revenue across all teams
25. **exp_men** Expenses for men's team
26. **exp_women** Expenses for women's team
27. **total_exp_menwomen** Expenses across both teams
28. **sports** Name of sport
